spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service


server:
  port: 6161


---
spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: stock_management
  datasource:
    url: "jdbc:postgresql://postgres:5432/stock_management"              #url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 12345

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}


---

